<?php
if (!defined('NV_ADMIN') || !defined('NV_MAINFILE') || !defined('NV_IS_MODADMIN'))
    die('Stop!!!');
$allow_func=[
    'main',
    'detail',
    'search',
    'category',
    'brand',
    'category/content',
    'category/add',
    'category/edit',
    'category/delete',
    'brands/content',
    'brands/add',
    'brands/edit',
    'brands/delete',
    'devices/content',
    'devices/add',
    'devices/edit',
    'devices/delete',
    'images/content',
    'images/add',
    'images/edit',
    'images/delete'
];