<!-- BEGIN: detail -->
<div class="nv-devices-detail">
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="mb-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{MODULE_URL}" class="text-decoration-none">{LANG.all_devices}</a></li>
            <li class="breadcrumb-item"><a href="{MODULE_URL}?cat_id=" class="text-decoration-none">{DEVICE.cat_title}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{DEVICE.title}</li>
        </ol>
    </nav>

    <div class="row">
        <!-- ============ LEFT: Image Gallery ============ -->
        <div class="col-lg-5 col-md-6 mb-4">
            <!-- Main Image (Carousel) -->
            <div id="deviceGallery" class="carousel carousel-indicators slide" data-bs-ride="carousel">
                <!-- Indicators (generated by JS if needed) -->
                <div class="carousel-inner">
                    <!-- Ảnh chính -->
                    <div class="carousel-item active">
                        <img src="{DEVICE.main_image}" alt="{DEVICE.title}" class="d-block w-100 rounded" style="height:380px; object-fit:cover;">
                    </div>
                    <!-- Ảnh thư viện -->
                    <!-- BEGIN: gallery_img -->
                    <div class="carousel-item">
                        <img src="{GALLERY.url}" alt="{GALLERY.note}" class="d-block w-100 rounded" style="height:380px; object-fit:cover;">
                    </div>
                    <!-- END: gallery_img -->
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#deviceGallery" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">{LANG.page_prev}</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#deviceGallery" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">{LANG.page_next}</span>
                </button>
            </div>

            <!-- Thumbnail Strip -->
            <div class="d-flex gap-2 mt-3 overflow-auto" id="thumbnailStrip">
                <img src="{DEVICE.main_image}" alt="" class="rounded border border-primary" style="width:70px; height:70px; object-fit:cover; cursor:pointer;" onclick="document.querySelector('#deviceGallery').carousel(0)">
                <!-- BEGIN: gallery_img -->
                <img src="{GALLERY.url}" alt="{GALLERY.note}" class="rounded" style="width:70px; height:70px; object-fit:cover; cursor:pointer;">
                <!-- END: gallery_img -->
            </div>
        </div>

        <!-- ============ RIGHT: Product Info ============ -->
        <div class="col-lg-7 col-md-6">
            <div class="mb-3">
                <span class="badge bg-light text-dark me-2">{DEVICE.cat_title}</span>
                <span class="badge bg-outline-secondary text-dark">{DEVICE.brand_title}</span>
            </div>

            <h2 class="fw-bold mb-2">{DEVICE.title}</h2>

            <div class="h4 text-primary mb-3">{DEVICE.price}</div>

            <p class="text-muted">{DEVICE.description}</p>

            <!-- Specs Table -->
            <div class="table-responsive mb-4">
                <table class="table table-sm table-bordered table-hover">
                    <tbody>
                        <tr>
                            <td class="fw-semibold text-muted" style="width:40%">{LANG.detail_brand}</td>
                            <td>{DEVICE.brand_title}</td>
                        </tr>
                        <tr>
                            <td class="fw-semibold text-muted">{LANG.detail_category}</td>
                            <td>{DEVICE.cat_title}</td>
                        </tr>
                        <tr>
                            <td class="fw-semibold text-muted">{LANG.detail_model}</td>
                            <td>{DEVICE.model_code}</td>
                        </tr>
                        <tr>
                            <td class="fw-semibold text-muted">{LANG.detail_quantity}</td>
                            <td>
                                {DEVICE.quantity}
                                <!-- BEGIN: in_stock -->
                                <span class="badge bg-success ms-2">{LANG.in_stock}</span>
                                <!-- END: in_stock -->
                                <!-- BEGIN: out_of_stock -->
                                <span class="badge bg-danger ms-2">{LANG.out_of_stock}</span>
                                <!-- END: out_of_stock -->
                            </td>
                        </tr>
                        <tr>
                            <td class="fw-semibold text-muted">{LANG.detail_date}</td>
                            <td>{DEVICE.created_time}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- Brand Support Link -->
            <a href="{MODULE_URL}" class="btn btn-outline-secondary btn-sm">
                <i class="fas fa-arrow-left me-1"></i>{LANG.back_to_list}
            </a>
        </div>
    </div>

    <!-- ============ FULL WIDTH: Chi tiết nội dung ============ -->
    <div class="row mt-5">
        <div class="col-12">
            <div class="card shadow-sm">
                <div class="card-header bg-white fw-semibold">{LANG.detail_content}</div>
                <div class="card-body">
                    <div class="nv-devices-content">
                        {DEVICE.content}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- ============ RELATED PRODUCTS ============ -->
    <div class="row mt-5">
        <div class="col-12">
            <h4 class="fw-semibold mb-3">{LANG.related_products}</h4>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-4">
                <!-- BEGIN: related_card -->
                <div class="col">
                    <div class="card h-100 shadow-sm border-0">
                        <a href="{RELATED.detail_url}" class="text-decoration-none">
                            <img src="{RELATED.image}" alt="{RELATED.title}" class="card-img-top" style="height:160px; object-fit:cover;">
                        </a>
                        <div class="card-body text-center">
                            <h6 class="card-title">
                                <a href="{RELATED.detail_url}" class="text-decoration-none text-dark">{RELATED.title}</a>
                            </h6>
                            <p class="text-primary fw-bold mb-0">{RELATED.price}</p>
                        </div>
                    </div>
                </div>
                <!-- END: related_card -->
            </div>
        </div>
    </div>
</div>
<!-- END: detail -->
